=head1 NAME

threads::tbb::blocked_int - a divisible range of integers

=head1 SYNOPSIS

  use threads::tbb;

  # a range, and a minimum quanta
  my $range = threads::tbb::blocked_int->new(1, 10, 1);

  print $range->size;         # 9
  print $range->begin;        # 1
  print $range->end;          # 10
  print $range->grainsize;    # 1
  print $range->is_divisible; # bool: 1 or ""
  print $range->empty;        # bool: 1 or ""

=head1 DESCRIPTION

This class lets you construct a C<tbb::blocked_rangeE<gt>intE<lt>>
range.  This is used for passing to functions such as
L<threads::tbb/parallel_for> to specify the iteration / division
space.

=head1 SEE ALSO

L<threads::tbb>

=cut

